# https://taskfile.dev

version: '3'

tasks:
  requirements:
    aliases:
      - "req"
    cmds:
      - poetry export -f requirements.txt --output requirements.txt --without-hashes --without-urls

  default:
    cmds:
      - python main.py

  publish:
    cmds:
      - poetry --build publish