# https://taskfile.dev

version: '3'

vars:
  INPUT: data/sample.filebeat.log
  POD: filebeat-rzlst
  NAMESPACE: kube-system
  CONTEXT: kind-multi-v1.23.5

tasks:
  requirements:
    aliases:
      - "req"
    cmds:
      - poetry export -f requirements.txt --output requirements.txt --without-hashes --without-urls

  default:
    cmds:
      - python main.py