# https://taskfile.dev

version: '3'

vars:
  INPUT: data/sample.filebeat.log
  POD: filebeat-rzlst
  NAMESPACE: kube-system
  CONTEXT: kind-multi-v1.23.5

tasks:
  requirements:
    aliases:
      - "req"
    cmds:
      - pip install --upgrade pip
      - pip install rich
      - pip install "rich[jupyter]"

  install-requirements:
    cmds:
      - pipenv requirements > requirements.txt
      - pyenv activate colored-logs-3.10.5
      - pip install -r requirements.txt

  default:
    cmds:
      - python main.py